CREATE TABLE CUSTOMER (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    FIRSTNAME NVARCHAR(40) NOT NULL,
    LASTNAME NVARCHAR(40) NOT NULL,
    CITY NVARCHAR(40) NOT NULL,
    COUNTRY NVARCHAR(40) NOT NULL,
    PHONE NVARCHAR(20) NOT NULL
);

CREATE TABLE ORDERS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    ORDERDATE DATE NOT NULL,
    ORDERNUMBER NVARCHAR(10) NOT NULL,
    CUSTOMERID INT NOT NULL,
    TOTALAMOUNT NUMERIC NOT NULL
);

CREATE TABLE ORDERITEM (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    ORDERID INT NOT NULL,
    PRODUCTID INT NOT NULL,
    UNITPRICE NUMERIC NOT NULL,
    QUANTITY INT NOT NULL
);

CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    PRODUCTNAME NVARCHAR(50) NOT NULL,
    SUPPLIERID INT ,
    UNITPRICE NUMERIC NOT NULL,
    PACKAGE NVARCHAR(30) NOT NULL,
    ISDISCONTINUED BOOLEAN NOT NULL
);

CREATE TABLE SUPPLIER (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    COMPANYNAME NVARCHAR(40) NOT NULL,
    CONTACTNAME NVARCHAR(50) NOT NULL,
    CONTACTTITLE NVARCHAR(40) NOT NULL,
    CITY NVARCHAR(40) NOT NULL,
    COUNTRY NVARCHAR(40) NOT NULL,
    PHONE NVARCHAR(40) NOT NULL,
    FAX NVARCHAR(40) NOT NULL
);
